DegitalContentManagerment/Controllers/AddressController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DegitalContentManagerment.Controllers
{
    public class AddressController : Controller
    {
        // GET: AddressController
        public ActionResult Index()
        {
            return View();
        }

        // GET: AddressController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: AddressController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AddressController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AddressController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: AddressController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AddressController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: AddressController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

DegitalContentManagerment/Controllers/AdminController.cs
using DegitalContentManagerment.Models.Admin;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DegitalContentManagerment.Controllers
{
    public class AdminController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;

        private readonly SignInManager<IdentityUser> _signInManager;

        public AdminController(SignInManager<IdentityUser> signInManager, UserManager<IdentityUser> userManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        [HttpGet]
        public IActionResult Register(string returnUrl=null)
        {
            returnUrl ??= Url.Content("~/");
            ViewBag.returnUrl = returnUrl;
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(RegisterModel model,String returnUrl=null)
        {
            returnUrl ??= Url.Content("~/");
            ViewBag.returnUrl = returnUrl;
            if (ModelState.IsValid)
            {
                var user = new IdentityUser
                {
                    UserName = model.User,
                    Email = model.Email
                };
                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    await _signInManager.PasswordSignInAsync(user, model.Password, false, false);
                    return LocalRedirect(returnUrl);
                }
                foreach(IdentityError item in result.Errors)
                {
                    ModelState.AddModelError("", item.Description);
                }

                return View(model);
            }
            return View(model);

        }
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Logout()
        {
            return View();
        }
        
    }
}

DegitalContentManagerment/Controllers/FacultyController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DegitalContentManagerment.Controllers
{
    public class FacultyController : Controller
    {
        // GET: FacultyController
        public ActionResult Index()
        {
            return View();
        }

        // GET: FacultyController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: FacultyController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: FacultyController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: FacultyController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: FacultyController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: FacultyController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: FacultyController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

DegitalContentManagerment/Controllers/LeturerController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.IO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DegitalContentManagerment.Models;
using DegitalContentManagerment.Data;




namespace DegitalContentManagerment.Controllers
{
    public class LeturerController : Controller
    {
        private readonly IWebHostEnvironment _env;
        private readonly DataContext _context;

        public LeturerController(IWebHostEnvironment env, DataContext context)
        {
            _env = env;
            _context = context;
        }

        // GET: LeturerController
        public ActionResult Index()
        {
            return View();
        }

        // GET: LeturerController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: LeturerController/Create
        public IActionResult Create()
        {
           
            return View("create");
        }

        // POST: LeturerController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Leturer leturer , IFormFile file)
        {
            if (file.Length>0 && file != null)
            {
                //var uploadFile = Path.GetFileName(file.FileName);
                //return Content($"{uploadFile}");
                var uploadFile = Path.GetFileName(file.FileName);
                var destination = Path.Combine(_env.WebRootPath, "Profiles", uploadFile);
                leturer.ImageFile = uploadFile;

                var fileStream = new FileStream(destination, FileMode.Create);
                await file.CopyToAsync(fileStream);

                await _context.Leturers.AddAsync(leturer);
                await _context.SaveChangesAsync();
            }
            return View("GetsAllProfile");
        }
        [HttpGet]
        public IActionResult GetsAllProfile()
        {
            var profiles = _context.Leturers.ToList();
            //return Json(profiles);
            return View("GetsAllProfile", profiles);
        }
        // GET: LeturerController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: LeturerController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: LeturerController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: LeturerController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

DegitalContentManagerment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DegitalContentManagerment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <!-- Custom fonts for this template-->
    <link href="~/font-awesome/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/startbootstrap-sb-admin-2/css/sb-admin-2.css" rel="stylesheet">

</head>
<body id="page-top">
    <div id="wrapper">
        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fa-solid fa-school"></i>
                </div>
                <div class="sidebar-brand-text mx-3"> DegitalCM</div>
            </a>
            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">
            <!-- Nav Item - Utilities Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
                   aria-expanded="true" aria-controls="collapseUtilities">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Table</span>
                </a>
                <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
                     data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Degital Content</h6>
                        <a class="collapse-item" asp-controller="Leturer" asp-action="Create">Leturer</a>
                        <a class="collapse-item" asp-controller="Student" asp-action="Create">Students</a>
                        <a class="collapse-item" asp-controller="Address" asp-action="Create">Address</a>
                        <a class="collapse-item" asp-controller="Faculty" asp-action="Create">Other</a>
                    </div>
                </div>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

           
        </ul>
        <!-- End of Sidebar -->
        <div id="content-wrapper" class="d-flex flex-column">
            <!-- Main Content -->
            <div id="content">
                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
                    <div class="container">
                        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DegitalContentManagerment</a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                                aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                                </li>
                            </ul>
                            <ul class="navbar-nav flex-grow-1 my-2 my-lg-0 ">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Login">Login</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Register">Register</a>
                                </li>
                            </ul>
                        </div>

                    </div>
                </nav>
            </div>
            <div class="container-fluid mb-4">
                <main>
                    @RenderBody()
                </main>
            </div>
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        &copy; 2022 - DegitalContentManagerment - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </div>
                </div>
            </footer>
        </div>
    </div>
            <!-- Custom scripts for all pages-->
            <script src="sb-admin-2.min.js"></script>
            <!-- Page level custom scripts -->
            <script src="~/jquery/jquery.min.js"></script>
            <script src="~/lib/jquery/dist/jquery.min.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
            @await RenderSectionAsync("Scripts", required: false)
</body>
</html>